# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FZHBlockLink' do

pod "YYModel"

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FZHBlockLink

  target 'FZHBlockLinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FZHBlockLinkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
